Fix #82 :: Space_Grotesk font-family & Some update ✅
GalsenDev221/website pull request #96
Opened 2024-01-26 18:39 UTC by daoodaba975

- [ ] Fix the Space_Grotesk font-family is not used in the navbar ( #82 )
- [ ] Update Telegram link

2024-01-26 20:04 UTC, NDOY3M4N requested changes
Just forgot to add the fonts in  `MobileMenu.tsx`

2024-01-26 22:47 UTC, daoodaba975 commented
> Just forgot to add the fonts in `MobileMenu.tsx`

Yes, I forgot about the mobile menu. I'll fix that quickly!

2024-01-26 23:25 UTC, daoodaba975 commented
@NDOY3M4N also fixing #97

2024-01-27 21:36 UTC, NDOY3M4N approved these changes

2024-01-27 21:39 UTC, merged